---
openapi: 3.1.0
info:
  description: Generated OpenAPI documentation
  title: coding-task-backend API
  version: 0.0.1
paths:
  /api/split:
    get:
      parameters:
        - name: total
          in: query
          schema:
            type: number
            pattern: "^\\d{1,7}([.]\\d{1,2})?$"
            maximum: 1000000
            minimum: 0.01
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
